# Hardware config database for FireSim Simulation Manager

# The AGFIs provided below are public and available to all users.
# Only AGFIs for the latest release of FireSim are guaranteed to be available.
# If you are using an older version of FireSim, you will need to generate your
# own images.

# DOCREF START: Example HWDB Entry
#firesim_boom_singlecore_nic_l2_llc4mb_ddr3:
#    agfi: agfi-0805da1f5da632561
#    deploy_quintuplet_override: null
#    deploy_makefrag_override: ../../generators/firechip/chip/src/main/makefrag/firesim
#    custom_runtime_config: null
# DOCREF END: Example HWDB Entry
firesim_boom_singlecore_nic_l2_llc4mb_ddr3:
    agfi: agfi-0805da1f5da632561
    deploy_quintuplet_override: null
    deploy_makefrag_override: ../../generators/firechip/chip/src/main/makefrag/firesim
    custom_runtime_config: null
firesim_boom_singlecore_no_nic_l2_llc4mb_ddr3:
    agfi: agfi-0ec7ae76159d3bfb6
    deploy_quintuplet_override: null
    deploy_makefrag_override: ../../generators/firechip/chip/src/main/makefrag/firesim
    custom_runtime_config: null
firesim_gemmini_printf_rocket_singlecore_no_nic:
    agfi: agfi-0f82901076822127a
    deploy_quintuplet_override: null
    deploy_makefrag_override: ../../generators/firechip/chip/src/main/makefrag/firesim
    custom_runtime_config: null
firesim_gemmini_rocket_singlecore_no_nic:
    agfi: agfi-0f567000cb21cb06d
    deploy_quintuplet_override: null
    deploy_makefrag_override: ../../generators/firechip/chip/src/main/makefrag/firesim
    custom_runtime_config: null
firesim_megaboom_singlecore_no_nic_l2_llc4mb_ddr3:
    agfi: agfi-0f4582f3f39b9a8a4
    deploy_quintuplet_override: null
    deploy_makefrag_override: ../../generators/firechip/chip/src/main/makefrag/firesim
    custom_runtime_config: null
firesim_rocket_quadcore_nic_l2_llc4mb_ddr3:
    agfi: agfi-013458e5c75f304a0
    deploy_quintuplet_override: null
    deploy_makefrag_override: ../../generators/firechip/chip/src/main/makefrag/firesim
    custom_runtime_config: null
firesim_rocket_quadcore_no_nic_l2_llc4mb_ddr3:
    agfi: agfi-0c5eedfce0e568971
    deploy_quintuplet_override: null
    deploy_makefrag_override: ../../generators/firechip/chip/src/main/makefrag/firesim
    custom_runtime_config: null
firesim_rocket_singlecore_no_nic_l2_lbp:
    agfi: agfi-033a86c6e5d006fc8
    deploy_quintuplet_override: null
    deploy_makefrag_override: ../../generators/firechip/chip/src/main/makefrag/firesim
    custom_runtime_config: null
firesim_saturn_GENV256D128_shuttle_singlecore_no_nic_l2_llc4mb_ddr3:
    agfi: agfi-065caaeb99b3363c4
    deploy_quintuplet_override: null
    deploy_makefrag_override: ../../generators/firechip/chip/src/main/makefrag/firesim
    custom_runtime_config: null
firesim_saturn_REFV256D128_rocket_singlecore_no_nic_l2_llc4mb_ddr3:
    agfi: agfi-012e92467d7d2149a
    deploy_quintuplet_override: null
    deploy_makefrag_override: ../../generators/firechip/chip/src/main/makefrag/firesim
    custom_runtime_config: null
vitis_firesim_rocket_singlecore_no_nic:
    bitstream_tar: https://raw.githubusercontent.com/firesim/firesim-public-bitstreams/11ba762decd46c5a933960eae699aaf551d6769f/vitis/vitis_firesim_rocket_singlecore_no_nic.tar.gz
    deploy_quintuplet_override: null
    deploy_makefrag_override: ../../generators/firechip/chip/src/main/makefrag/firesim
    custom_runtime_config: null
vitis_firesim_gemmini_rocket_singlecore_no_nic:
    bitstream_tar: https://raw.githubusercontent.com/firesim/firesim-public-bitstreams/0af81b912264abbe3f90f8140987814291090560/vitis/vitis_firesim_gemmini_rocket_singlecore_no_nic.tar.gz
    deploy_quintuplet_override: null
    deploy_makefrag_override: ../../generators/firechip/chip/src/main/makefrag/firesim
    custom_runtime_config: null
alveo_u250_firesim_rocket_singlecore_no_nic:
    bitstream_tar: https://github.com/firesim/firesim-public-bitstreams/raw/b31b0c9571f8b9725cf9864a3221face63535a94/xilinx_alveo_u250/alveo_u250_firesim_rocket_singlecore_no_nic.tar.gz
    deploy_quintuplet_override: null
    deploy_makefrag_override: ../../generators/firechip/chip/src/main/makefrag/firesim
    custom_runtime_config: null
alveo_u250_firesim_rocket_quadcore_no_nic:
    bitstream_tar: https://github.com/firesim/firesim-public-bitstreams/raw/b31b0c9571f8b9725cf9864a3221face63535a94/xilinx_alveo_u250/alveo_u250_firesim_rocket_quadcore_no_nic.tar.gz
    deploy_quintuplet_override: null
    deploy_makefrag_override: ../../generators/firechip/chip/src/main/makefrag/firesim
    custom_runtime_config: null
alveo_u250_firesim_boom_singlecore_no_nic:
    bitstream_tar: https://github.com/firesim/firesim-public-bitstreams/raw/b31b0c9571f8b9725cf9864a3221face63535a94/xilinx_alveo_u250/alveo_u250_firesim_boom_singlecore_no_nic.tar.gz
    deploy_quintuplet_override: null
    deploy_makefrag_override: ../../generators/firechip/chip/src/main/makefrag/firesim
    custom_runtime_config: null
alveo_u250_firesim_rocket_singlecore_nic:
    bitstream_tar: https://raw.githubusercontent.com/firesim/firesim-public-bitstreams/d8e0d2535f2cae6834d8acc25fdc0c9c26230d28/xilinx_alveo_u250/alveo_u250_firesim_rocket_singlecore_nic.tar.gz
    deploy_quintuplet_override: null
    deploy_makefrag_override: ../../generators/firechip/chip/src/main/makefrag/firesim
    custom_runtime_config: null
alveo_u250_firesim_gemmini_rocket_singlecore_no_nic:
    bitstream_tar: https://github.com/firesim/firesim-public-bitstreams/raw/b31b0c9571f8b9725cf9864a3221face63535a94/xilinx_alveo_u250/alveo_u250_firesim_gemmini_rocket_singlecore_no_nic.tar.gz
    deploy_quintuplet_override: null
    deploy_makefrag_override: ../../generators/firechip/chip/src/main/makefrag/firesim
    custom_runtime_config: null
alveo_u250_firesim_saturn_GENV256D128_shuttle_singlecore_no_nic:
    bitstream_tar: https://github.com/firesim/firesim-public-bitstreams/raw/b31b0c9571f8b9725cf9864a3221face63535a94/xilinx_alveo_u250/alveo_u250_firesim_saturn_GENV256D128_shuttle_singlecore_no_nic.tar.gz
    deploy_quintuplet_override: null
    custom_runtime_config: null
alveo_u250_firesim_saturn_REFV256D128_rocket_singlecore_no_nic:
    bitstream_tar: https://github.com/firesim/firesim-public-bitstreams/raw/b31b0c9571f8b9725cf9864a3221face63535a94/xilinx_alveo_u250/alveo_u250_firesim_saturn_REFV256D128_rocket_singlecore_no_nic.tar.gz
    deploy_quintuplet_override: null
    custom_runtime_config: null
alveo_u200_firesim_rocket_singlecore_no_nic:
    bitstream_tar: https://raw.githubusercontent.com/firesim/firesim-public-bitstreams/357c8268872ea107e5877b140b470f9ba20ea7ff/xilinx_alveo_u200/alveo_u200_firesim_rocket_singlecore_no_nic.tar.gz
    deploy_quintuplet_override: null
    deploy_makefrag_override: ../../generators/firechip/chip/src/main/makefrag/firesim
    custom_runtime_config: null
alveo_u280_firesim_rocket_singlecore_no_nic:
    bitstream_tar: https://raw.githubusercontent.com/firesim/firesim-public-bitstreams/5718958b05ada4d35197b04d27132439ad1b8aae/xilinx_alveo_u280/alveo_u280_firesim_rocket_singlecore_no_nic.tar.gz
    deploy_quintuplet_override: null
    deploy_makefrag_override: ../../generators/firechip/chip/src/main/makefrag/firesim
    custom_runtime_config: null
xilinx_vcu118_firesim_rocket_singlecore_4GB_no_nic:
    bitstream_tar: https://github.com/firesim/firesim-public-bitstreams/raw/b31b0c9571f8b9725cf9864a3221face63535a94/xilinx_vcu118/xilinx_vcu118_firesim_rocket_singlecore_4GB_no_nic.tar.gz
    deploy_quintuplet_override: null
    deploy_makefrag_override: ../../generators/firechip/chip/src/main/makefrag/firesim
    custom_runtime_config: null
nitefury_firesim_rocket_singlecore_no_nic:
    bitstream_tar: https://raw.githubusercontent.com/firesim/firesim-public-bitstreams/4fed63d5a4836de28ac69edf2620d304615572c9/rhsresearch_nitefury_ii/nitefury_firesim_rocket_singlecore_no_nic.tar.gz
    deploy_quintuplet_override: null
    deploy_makefrag_override: ../../generators/firechip/chip/src/main/makefrag/firesim
    custom_runtime_config: null
